xpress/config/routes.rb
Xpress::Application.routes.draw do

  resources :requests

  resources :books

	devise_for :users, :controllers => { :registrations => "registration", :sessions => "sess" }
    get "admincontroller/adminhome"
    get "admincontroller/adminrole"
get "users/userhome"
get "users/activeusers"
get "users/inactiveusers"
get "users/issuerequest"
post "users/approvemsg"
post "requests/neww"
get "requests/show"
get '/details/', :controller=>'details', :action=>'index'
get '/details/:id', :controller=>'details', :action=>'show'
get '/details/edit', :controller => :details, :action => :edit

   root 'welcome#index'

  

end

xpress/app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  
end

xpress/app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
	@requests = Request.all
        @detail=Detail.new

=begin
@requests = Request.paginate(:page => params[:page], :order => 'created_at desc', :per_page => 2)
=end
	render :layout=>'ajax'
  end
  def neww
	@book = Book.new
	@request = Request.new
	@book.id = params[:book_id].to_i
	@request.book_id = @book.id
	@request.request_status="Pending"
	@request.user_id=current_user.id









=begin
	@request = Request.new
	@request.book = params[:book_id]
	@request.user= current_user.id
	render text: book_id.inspect
	render text: userId.inspect
	#@request.request_status="Pending"
=end
  end	
  # GET /requests/1
  # GET /requests/1.json
  def show
	
  end

  # GET /requests/new
  def new
    @request = Request.new
	
	
  end

  # GET /requests/1/edit
  def edit
	
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @request }
      else
        format.html { render action: 'new' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
  

    respond_to do |format|
      if @request.update(request_params)
         bookid=@request.book_id
		@book=Book.find(bookid)
                if @request.request_status=="Approved"
                    @book.user_id=@request.user_id
		    
                    @book.status="Issued"
                        @book.save
		    @detail=Detail.find(@book.user_id)
			@detail.noofbooksissued=@detail.noofbooksissued+1
				@detail.save                        
                               
		end

        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
                        
                  
      else
        format.html { render action: 'edit' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:request_status, :user_id, :book_id)
    end
end

xpress/app/helpers/requests_helper.rb
module RequestsHelper
end

xpress/app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table align="center">
    <tr><td><%= f.label :request_status %></td>
<td><%if current_user.role.role!="admin"%>
    <%= f.text_field :request_status, :value=>"Pending", :readonly=>:readonly %>
<%else%>
<%= f.select :request_status, options_for_select(%w[Pending Approved]) %>
<%end%></td></tr>
 <tr><td>
    <%= f.label :user %></td>
    <td><%= f.text_field :user_id, :readonly=>:readonly %></td></tr>
 <tr><td>
    <%= f.label :book %></td>
    <td><%= f.text_field :book_id, :readonly=>:readonly %></td></tr>
  
  <tr><td colspan="2"><center>
    <%= f.submit %></center></td></tr>
  
  </table>
<% end %>

xpress/app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', admincontroller_adminhome_path %>

xpress/app/views/requests/index.html.erb
<script>
	$(function() {
		$( "#tabs" ).tabs({
			beforeLoad: function( event, ui ) {
				ui.jqXHR.error(function() {
					ui.panel.html("Couldn't load this tab. We'll try to fix this as soon as possible. If this wouldn't be 						a demo." );
				});
			}
		});
	});
</script>








<h1>Listing requests</h1>

<table align="center" border="1" width=600px>
  <thead>
    <tr>
      <th>Request status</th>
      <th>User_id</th>
      <th>Book_id</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.request_status %></td>
        <td><%= request.user.id %></td>
        <td><%= request.book_id %></td>
	
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<td>
<%
	@detail.user_id=request.user_id
	@detail=Detail.find(@detail.user_id)
	firstname=@detail.firstname
	num=@detail.noofbooksissued
%>

<%if (num.to_i > 2) %>
<%= image_tag("index.jpg") %>
<% end %>

                </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<br>

xpress/app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

xpress/app/views/requests/neww.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', users_userhome_path %>

xpress/app/views/requests/show.html.erb
<table align="center">
  <tr><td><strong>Request status:</strong></td>
  <td><%= @request.request_status %></td></tr>

   <tr><td><strong>User:</strong></td>
  <td><%= @request.user.id %></td></tr>


  <tr><td><strong>Book:</strong></td>
  <td><%= @request.book_id %></td></tr>
</table>


<%if current_user.role.role=="admin"  %>
<%= link_to 'Edit', edit_request_path(@request) %>
 |
<%= link_to 'Back', admincontroller_adminhome_path %>
<% else%>

<%= link_to 'Back', users_userhome_path %>
<%end%>