xpress/config/routes.rb
Xpress::Application.routes.draw do

  resources :requests

  resources :books

	devise_for :users, :controllers => { :registrations => "registration", :sessions => "sess" }
    get "admincontroller/adminhome"
    get "admincontroller/adminrole"
get "users/userhome"
get "users/activeusers"
get "users/inactiveusers"
get "users/issuerequest"
post "users/approvemsg"
post "requests/neww"
get "requests/show"
get '/details/', :controller=>'details', :action=>'index'
get '/details/:id', :controller=>'details', :action=>'show'
get '/details/edit', :controller => :details, :action => :edit

   root 'welcome#index'

  

end

xpress/app/models/book.rb
class Book < ActiveRecord::Base
 has_many :requests
 belongs_to :user
 validates :book_title, presence: true
 validates :author_name, presence: true
 validates :no_of_pages, presence: true
end

xpress/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
	
render :layout=>'ajax'
  end

  # GET /books/1
  # GET /books/1.json
  def show
	
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book].permit(:book_title,:author_name,:no_of_pages,:book_type,:status,:releasedate))

 respond_to do |format|
      if @book.save
       format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_title, :author_name, :no_of_pages, :book_type,:releasedate)
    end
end

xpress/app/helpers/books_helper.rb
module BooksHelper
end

xpress/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table align="center"><tr><td>
    <%= f.label :book_Title %></td>
    <td><%= f.text_field :book_title %></td></tr>
 
<tr><td>    <%= f.label :author_name %></td>
    <td><%= f.text_field :author_name %></td></tr>
 
   <tr><td> <%= f.label :no_of_pages %></td>
    <td><%= f.number_field :no_of_pages %></td></tr>
  
    <tr><td><%= f.label :book_type %></td>
    <td><%= f.select :book_type, options_for_select(%w[Fiction Inspirational Technical]) %></td></tr>
    
  
  <tr><td>  <%= f.label :status %></td>
    <td><%= f.text_field :status, :value=>"Available", :readonly=>:readonly %></td></tr>
  

<tr><td>  <%= f.label :releasedate %></td>
    <td><%= f.date_select :releasedate  %></td></tr>

    <tr><td colspan="2"><center><%= f.submit %></center></td></tr>
  </table>
<% end %>

xpress/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', admincontroller_adminhome_path %>

xpress/app/views/books/index.html.erb
<h1>Listing books</h1>

<table align="center" border=1px width=600px>
  <thead>
    <tr>
      <th>Book Title</th>&nbsp;
      <th>Author name</th>&nbsp;
      <th>No of pages</th>&nbsp;
      <th>Book type</th>&nbsp;
      <th>Release date</th>&nbsp;
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book_title %></td>
        <td><%= book.author_name %></td>
        <td><%= book.no_of_pages %></td>
        <td><%= book.book_type %></td>
        <td><%= book.releasedate %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Book', new_book_path %>
<%= link_to 'Home', admincontroller_adminhome_path %>

xpress/app/views/books/new.html.erb
<h1><u>New book</u></h1>

<%= render 'form' %>
</br>
<%= link_to 'Back', admincontroller_adminhome_path %>

xpress/app/views/books/show.html.erb
<%= form_tag(requests_neww_path, :method=>:post)%>

</br>
<table align="center" height=200px border=1><tr><td>
  <strong>Book Title:</strong></td>
  <td><%= @book.book_title %></td></tr>

  <tr><td><strong>Author name:</strong></td>
  <td><%= @book.author_name %></td></tr>

  <tr><td><strong>No of pages:</strong></td>
 <td> <%= @book.no_of_pages %></td></tr>
 
 <tr><td> <strong>Book type:</strong></td>
 <td> <%= @book.book_type %></td></tr>

<tr><td><strong>Status:</strong></td>
 <td> <%= @book.status %></td></tr>


<tr><td><strong>Release Date:</strong></td>
 <td> <%= @book.releasedate %></td></tr>
  
<tr><td><strong>Book_id:  </strong></td>
<td><input type='text' name='book_id' value='<%= @book.id %>' readonly='readonly' style="border:transparent;background:#ECECEC"/></td></tr>
</table>
</br>
<%if current_user.role.role=="admin"  %>
<%= link_to 'Edit', edit_book_path(@book) %>
 |
<%= link_to 'Back', admincontroller_adminhome_path %>
<% else%>
<%= submit_tag("Raise Issue Request") %>


|
<%= link_to 'Back', users_userhome_path %>
<%end%>
</form>