xpress/config/routes.rb
Xpress::Application.routes.draw do

  resources :requests

  resources :books

	devise_for :users, :controllers => { :registrations => "registration", :sessions => "sess" }
    get "admincontroller/adminhome"
    get "admincontroller/adminrole"
get "users/userhome"
get "users/activeusers"
get "users/inactiveusers"
get "users/issuerequest"
post "users/approvemsg"
post "requests/neww"
get "requests/show"
get '/details/', :controller=>'details', :action=>'index'
get '/details/:id', :controller=>'details', :action=>'show'
get '/details/edit', :controller => :details, :action => :edit

   root 'welcome#index'

  

end

xpress/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :detail
  has_one :role
  has_many :requests
  has_many :books
end

xpress/app/controllers/users_controller.rb
class UsersController < ApplicationController
def userhome

end

def issuerequest
 @books=Book.find(:all)
render :layout=>'ajax'
end
def activeusers
 @users=User.find(:all)
 @books=Book.find(:all)
 @details=Detail.find(:all)
if user_signed_in?
	session[:act] = "activeusers"
end
render :layout=>'ajax'
end
def inactiveusers
 @users=User.find(:all)
 @books=Book.find(:all)
 @details=Detail.find(:all)
 render :layout=>'ajax'
end
def approvemsg
	book_id = params[:book_id]
	userId= current_user.id
	#render text: book_id.inspect
	render text: userId.inspect
	request_status="Pending"
end
end

xpress/app/helpers/users_helper.rb
module UsersHelper
end

xpress/app/views/users/activeusers.html.erb
<h1><center>All Active Users</center></h1>
<table align="center">
<% for detail in @details %>
<% for book in @books %>
<%if(detail.user_id==book.user_id)%>



<tr><td><a href="/details/<%=detail.user_id%>"><%=detail.firstname%></a></td></tr>
<% break -%>


<%end%>
<%end%>
<%end%>

</table>

xpress/app/views/users/approvemsg.html.erb
<h1><center>Your Request For Issue This Book Has Been Sent For Approval!!</center></h1>

xpress/app/views/users/inactiveusers.html.erb
<h1><center>All Inactive Users</center></h1>

<% for detail in @details %>
<% for book in @books %>
<%if ((detail.user_id!=book.user_id)&& (!(detail.noofbooksissued.to_i >= 1)) )%>

<%flag=1%>
<%else%>
<%flag=0%>
<%end%>

<%end%>
<%if flag==1%>
<table align="center">
<tr><td><a href="/details/<%=detail.user_id%>"><%=detail.firstname%></a></td></tr>
<%end%>

<%end%>

</table>

xpress/app/views/users/issuerequest.html.erb
<h1><center>All Available Books</center></h1>

<% for book in @books %>
<%if(book.status=="Available")%>
<table align="center">
<tr><td><a href="/books/<%=book.id%>"><%=book.book_title%></a></td></tr>

<%end%>
<%end%>

</table>

xpress/app/views/users/show.html.erb
<h1>User Details</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @detail.firstname %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @detail.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @detail.address %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @detail.contact %>
</p>

<h1>Issue Details</h1>

<%= link_to 'Back', admincontroller_adminrole_path %>

xpress/app/views/users/userhome.html.erb
<script>
	$(function() {
		$( "#tabs" ).tabs({
			beforeLoad: function( event, ui ) {
				ui.jqXHR.error(function() {
					ui.panel.html("Couldn't load this tab. We'll try to fix this as soon as possible. If this wouldn't be 						a demo." );
				});
			}
		});
	});
</script>



<div id="tabs">
<ul>
<li><a href="#tabs-1">Home</a></li>

<li><a href="/details/<%=current_user.id%>">Show my details</a></li>
<li><%=link_to 'Raise Issue Request', users_issuerequest_path %></li>


</ul>
<div id="tabs-1">
<p><h1><center>Welcome  <%=current_user.detail.firstname %>!!</center></h1></p>
</div>
</div>